name: GLAMOUR
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.9
  - ipykernel
  - pytorch=2.3.1         # CUDA-enabled build
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1     # CUDA 12.1 support
  - rdkit
  - numpy=1.23.0
  - pip
  - pip:
    - dgl==0.9.2.post2    # match your CUDA/PyTorch version
    - dgllife
    - GraKeL
    - pydantic
    - captum
    - matplotlib
    - seaborn
    - optuna
    - optunahub
    - HEBO
    - pyarrow
